services:
  db:
    image: postgres:17
    container_name: pulso-db
    restart: always
    environment:
      POSTGRES_DB: pulso
      POSTGRES_USER: pulso
      POSTGRES_PASSWORD: pulso123@#
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pulso:
    build: .
    container_name: pulso-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    restart: always

volumes:
  pgdata:
